### PR TITLE
Odoo 8.0 instance

### PR DESCRIPTION
**Pull request by ruiztulio**
The main idea of this PR is to have an Odoo 8.0 instance with public repos only, so it can be used for testing purposes. The image will be hosted in hub.docker.com, public and associated with this repo

### CODE REVIEW

**Comment by ruiztulio** [comment]
@moylop260 do you agree with this?

**Comment by moylop260** [comment]
Hello @ruiztulio 
I'm confusing with https://github.com/Vauxoo/docker-odoo-image/tree/master/odoo80
Can change the name?

**Comment by ruiztulio** [comment]
@moylop260  That one is the base image for all Odoo 8.0 Images. But now I changed it to test80

**Comment by moylop260** [comment]
:+1:

**Pull request merged**
